version: '3'

volumes:
  static:
  media:
  pg_data:
  nginx-data:

networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
  backend:
    image: d2avids/iskra:latest
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    volumes:
      - ./logs:/app/logs
      - static:/backend_static/static
      - media:/app/media
    networks:
      - internal
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=360
      - GUNICORN_MAX_REQUESTS=1000
      - GUNICORN_MAX_REQUESTS_JITTER=100
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/v1/educational_organizations/ || exit 1" ]
      interval: 15s
      timeout: 7s
      retries: 3
  celery_worker:
    image: d2avids/iskra:latest
    restart: always
    env_file: .env
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./logs:/app/logs
      - media:/app/media
    depends_on:
      - backend
    networks:
      - internal
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./nginx_internal.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
