# Generated by Django 5.0.6 on 2024-07-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='educational_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.educationalorganization', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='competencies',
            field=models.TextField(blank=True, null=True, verbose_name='Компетенции'),
        ),
    ]
