# Generated by Django 5.0.6 on 2024-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_educational_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional_competencies',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Профессиональные компетенции'),
        ),
    ]
