# Generated by Django 5.0.6 on 2024-07-14 12:31

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_professional_competencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.users_files_path, verbose_name='Фото'),
        ),
    ]
