# Generated by Django 5.0.6 on 2024-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usertestanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('director', 'Руководитель'), ('parent', 'Родитель')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
